services:
    milk-collection:
        image: "edwarddocker270/milk-collection:s4"
        container_name: milk-collection-ms
        ports:
            - "8080:8080"
        deploy:
            resources:
                limits:
                    memory: 500M
        networks:
            - milk-plant-network

    persons:
        image: "edwarddocker270/persons:s4"
        container_name: persons-ms
        ports:
            - "9090:9090"
        deploy:
            resources:
                limits:
                    memory: 700M
        networks:
            - milk-plant-network

    financial-management:
        image: "edwarddocker270/financial-management:s4"
        container_name: financial-management-ms
        ports:
            - "7070:7070"
        deploy:
            resources:
                limits:
                    memory: 500M
        networks:
            - milk-plant-network

networks:
    milk-plant-network:
        driver: "bridge"
