spring:
  application:
    name: "Gateway-Server"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted #enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "Gateway-Server"
    description: "Gateway Server microservice"
    version: "1.0.0"

logging:
  level:
    com:
      module:
        Gateway_Server: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000