services:
    rabbit:
        image: rabbitmq:3.13-management
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 5s
        extends:
            file: common-config.yml
            service: network-deploy-service

    config-server-s:
        image: "edwarddocker270/config-server:s6"
        container_name: config-server-ms
        ports:
            - "8071:8071"
        extends:
            file: common-config.yml
            service: microservice-base-config
        depends_on:
            rabbit:
                condition: service_healthy
        healthcheck:
            test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s

    milk-collection-s:
        image: "edwarddocker270/milk-collection:s6"
        container_name: milk-collection-ms
        ports:
            - "8080:8080"
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            SPRING_APPPLICATION_NAME: "Milk-Collection"
        depends_on:
            config-server-s:
                condition: service_healthy

    persons-s:
        image: "edwarddocker270/persons:s6"
        container_name: persons-ms
        ports:
            - "9090:9090"
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            SPRING_APPPLICATION_NAME: "Persons"
        depends_on:
            config-server-s:
                condition: service_healthy

    financial-management-s:
        image: "edwarddocker270/financial-management:s6"
        container_name: financial-management-ms
        ports:
            - "7070:7070"
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            SPRING_APPPLICATION_NAME: "Financial-Management"
        depends_on:
            config-server-s:
                condition: service_healthy

networks:
    milk-plant-network:
        driver: "bridge"


