services:

    milk-collection-db:
        container_name: milk-collection-db
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: milk-collection-db
        extends:
            file: common-config.yml
            service: microservice-db-config

    persons-db:
        container_name: persons-db
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: persons-db
        extends:
            file: common-config.yml
            service: microservice-db-config

    financial-management-db:
        container_name: financial-management-db
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: financial-management-db
        extends:
            file: common-config.yml
            service: microservice-db-config

    config-server-s:
        image: "edwarddocker270/config-server:s6"
        container_name: config-server-ms
        ports:
            - "8071:8071"
        extends:
            file: common-config.yml
            service: microservice-base-config
        healthcheck:
            test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s

    milk-collection-s:
        image: "edwarddocker270/milk-collection:s6"
        container_name: milk-collection-ms
        ports:
            - "8080:8080"
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            SPRING_APPPLICATION_NAME: "Milk-Collection"
            SPRING_DATASOURCE_URL: "jdbc:mysql://milk-collection-db:3306/milk-collection-db"
        depends_on:
            milk-collection-db:
                condition: service_healthy
            config-server-s:
                condition: service_healthy

    persons-s:
        image: "edwarddocker270/persons:s6"
        container_name: persons-ms
        ports:
            - "9090:9090"
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            SPRING_APPPLICATION_NAME: "Persons"
            SPRING_DATASOURCE_URL: "jdbc:mysql://persons-db:3307/persons-db"
        depends_on:
            persons-db:
                condition: service_healthy
            config-server-s:
                condition: service_healthy

    financial-management-s:
        image: "edwarddocker270/financial-management:s6"
        container_name: financial-management-ms
        ports:
            - "7070:7070"
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            SPRING_APPPLICATION_NAME: "Financial-Management"
            SPRING_DATASOURCE_URL: "jdbc:mysql://financial-management-db:3308/financial-management-db"
        depends_on:
            financial-management-db:
                condition: service_healthy
            config-server-s:
                condition: service_healthy

networks:
    milk-plant-network:
        driver: "bridge"


