global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'milk-collection-service'
    metrics_path: '/actuator/milk-collection/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Milk Collection Service'
  - job_name: 'orders-service'
    metrics_path: '/actuator/orders/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Orders Service'
  - job_name: 'inventory-service'
    metrics_path: '/actuator/inventory/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Inventory Service'