spring:
    application:
        name: "Config-Server"
    profiles:
        active: native
    cloud:
      config:
        server:
          native:
            #search-locations: "classpath:/config"
            search-locations: "file:///C://Users//Cyborg//Documents//Courses//Utils//spring-cloud-config//config"

server:
    port: 8071
