# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: persons-deployment
serviceName: persons
appLabel: persons
appName: Persons

replicaCount: 1

image:
  repository: edwarddocker270/persons
  tag: s17

containerPort: 8180

service:
  type: ClusterIP
  port: 8180
  targetPort: 8180

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
db_enabled: true

db:
  pvcName: persons-db-pvc
  pvcStorage: 300Mi
  deploymentName: persons-db-deployment
  deploymentLabel: persons-db-label
  initialDataBase: persons-db
  serviceName: persons-db-service
  service:
    type: ClusterIP
    port: 3307
    targetPort: 3306
  datasourceURL: "jdbc:mysql://persons-db-service:3307/persons-db"