# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: financial-management-deployment
serviceName: financial-management
appLabel: financial-management
appName: Financial-Management

replicaCount: 1

image:
  repository: edwarddocker270/financial-management
  tag: s17

containerPort: 8280

service:
  type: ClusterIP
  port: 8280
  targetPort: 8280

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
db_enabled: true

db:
  pvcName: financial-management-db-pvc
  pvcStorage: 300Mi
  deploymentName: financial-management-db-deployment
  deploymentLabel: financial-management-db-label
  initialDataBase: financial-management-db
  serviceName: financial-management-db-service
  service:
    type: LoadBalancer
    port: 3308
    targetPort: 3306
  datasourceURL: "jdbc:mysql://financial-management-db-service:3308/financial-management-db"