# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: financial-management-deployment
serviceName: financial-management
appLabel: financial-management
appName: financial-management

replicaCount: 1

image:
  repository: edwarddocker270/financial-management
  tag: s14

containerPort: 8280

service:
  type: ClusterIP
  port: 8280
  targetPort: 8280

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false